#!/usr/bin/env python3
"""一键打包脚本：自动版本号管理 + PyInstaller + Inno Setup

用法:
    python build_release.py                  # 自动递增 patch 版本
    python build_release.py --bump minor     # 递增 minor 版本
    python build_release.py --bump major     # 递增 major 版本
    python build_release.py --version 2.0.0  # 指定版本号
    python build_release.py --no-bump        # 不修改版本号，直接打包
    python build_release.py --skip-installer # 只打 exe，不打安装包
"""

import argparse
import os
import platform
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# ── 路径 ──
PROJECT_DIR = Path(__file__).parent
VERSION_FILE = PROJECT_DIR / "VERSION"
DIST_DIR = PROJECT_DIR / "dist" / "vocab-harvester"
INSTALLER_DIR = PROJECT_DIR / "installer"
ICON_FILE = PROJECT_DIR / "icon.ico"

# Inno Setup 路径
ISCC_PATHS = [
    Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Inno Setup 6" / "ISCC.exe",
    Path("C:/Program Files (x86)/Inno Setup 6/ISCC.exe"),
    Path("C:/Program Files/Inno Setup 6/ISCC.exe"),
]


def read_version() -> str:
    if VERSION_FILE.exists():
        return VERSION_FILE.read_text(encoding="utf-8").strip()
    return "0.0.0"


def write_version(version: str):
    VERSION_FILE.write_text(version + "\n", encoding="utf-8")


def bump_version(current: str, part: str) -> str:
    major, minor, patch = (int(x) for x in current.split("."))
    if part == "major":
        return f"{major + 1}.0.0"
    elif part == "minor":
        return f"{major}.{minor + 1}.0"
    else:
        return f"{major}.{minor}.{patch + 1}"


def find_iscc() -> Path | None:
    for p in ISCC_PATHS:
        if p.exists():
            return p
    return None


def run(cmd: list[str], cwd=None, check=True):
    print(f"  > {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if result.stdout:
        for line in result.stdout.strip().split("\n")[-5:]:
            print(f"    {line}")
    if result.returncode != 0 and check:
        print(f"  [FAIL] exit code {result.returncode}")
        if result.stderr:
            for line in result.stderr.strip().split("\n")[-10:]:
                print(f"    {line}")
        sys.exit(1)
    return result


def generate_setup_iss(version: str, source_dir: str, output_dir: str) -> str:
    """生成 Inno Setup 脚本内容"""
    icon_escaped = str(ICON_FILE).replace("\\", "/")
    return f'''; Auto-generated by build_release.py - version {version}
#define MyAppName "vocab-harvester"
#define MyAppVersion "{version}"
#define MyAppPublisher "VocabHarvester"
#define MyAppExeName "vocab-harvester.exe"
#define MySourceDir "{source_dir}"

[Setup]
AppId={{{{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
DisableProgramGroupPage=yes
OutputDir={output_dir}
OutputBaseFilename=vocab-harvester-{version}-setup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
SetupIconFile={icon_escaped}
UninstallDisplayIcon={{app}}\\{{#MyAppExeName}}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"

[Files]
Source: "{{#MySourceDir}}\\{{#MyAppExeName}}"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "{{#MySourceDir}}\\_internal\\*"; DestDir: "{{app}}\\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; WorkingDir: "{{app}}"; Flags: nowait postinstall skipifsilent
'''


def main():
    parser = argparse.ArgumentParser(description="vocab-harvester 一键打包")
    parser.add_argument("--bump", choices=["major", "minor", "patch"], default="patch", help="递增版本号部分")
    parser.add_argument("--version", type=str, help="指定版本号（跳过自动递增）")
    parser.add_argument("--no-bump", action="store_true", help="不修改版本号")
    parser.add_argument("--skip-installer", action="store_true", help="只打 exe，不打安装包")
    parser.add_argument("--skip-tests", action="store_true", help="跳过测试")
    args = parser.parse_args()

    # 确保 Windows
    if platform.system() != "Windows":
        print("[WARN] Inno Setup 仅支持 Windows，将跳过安装包编译")
        args.skip_installer = True

    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    # ── 版本号 ──
    current_version = read_version()
    if args.version:
        new_version = args.version
    elif args.no_bump:
        new_version = current_version
    else:
        new_version = bump_version(current_version, args.bump)

    print(f"[*] Version: {current_version} -> {new_version}" if not args.no_bump else f"[*] Version: {new_version}")
    write_version(new_version)

    # ── 测试（可选）──
    if not args.skip_tests:
        print("\n[*] Running tests...")
        result = run([sys.executable, "-m", "pytest", "tests/", "-x", "-q", "--tb=short"],
                     cwd=str(PROJECT_DIR), check=False)
        if result.returncode != 0:
            print("[!] Tests failed. Use --skip-tests to skip.")
            sys.exit(1)
        print("[OK] Tests passed")
    else:
        print("[*] Skipping tests")

    # ── 清理旧构建 ──
    print("\n[*] Cleaning old build...")
    for d in [PROJECT_DIR / "dist", PROJECT_DIR / "build"]:
        if d.exists():
            shutil.rmtree(d)
    print("[OK] Clean done")

    # ── PyInstaller ──
    print("\n[*] Running PyInstaller...")
    run([sys.executable, "-m", "PyInstaller", "build.spec", "--noconfirm"], cwd=str(PROJECT_DIR))

    if not (DIST_DIR / "vocab-harvester.exe").exists():
        print("[FAIL] PyInstaller did not produce exe")
        sys.exit(1)

    dist_size = sum(f.stat().st_size for f in DIST_DIR.rglob("*") if f.is_file()) / (1024 * 1024)
    print(f"[OK] exe built ({dist_size:.0f} MB)")

    if args.skip_installer:
        print(f"\n=== Done! v{new_version} (exe only) ===")
        return

    # ── Inno Setup ──
    iscc = find_iscc()
    if not iscc:
        print("[WARN] Inno Setup not found, skipping installer")
        print(f"\n=== Done! v{new_version} (exe only, no ISCC) ===")
        return

    # 复制到短路径以避免 MAX_PATH 问题
    short_base = Path("C:/temp/vh_build")
    if short_base.exists():
        shutil.rmtree(short_base)
    short_dist = short_base / "vocab-harvester"
    short_installer = short_base / "installer"
    short_dist.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(DIST_DIR, short_dist)
    short_installer.mkdir(parents=True, exist_ok=True)

    # 生成 .iss
    iss_content = generate_setup_iss(
        new_version,
        str(short_dist).replace("\\", "/"),
        str(short_installer).replace("\\", "/"),
    )
    iss_file = short_base / "setup.iss"
    iss_file.write_text(iss_content, encoding="utf-8")

    print(f"\n[*] Running Inno Setup ({iscc})...")
    result = run([str(iscc), str(iss_file)], check=False)

    # 查找输出的安装包
    installer_files = list(short_installer.glob("*.exe"))
    if not installer_files:
        print("[FAIL] Inno Setup did not produce installer")
        # 清理临时目录
        shutil.rmtree(short_base, ignore_errors=True)
        sys.exit(1)

    # 复制到项目 installer/ 目录
    INSTALLER_DIR.mkdir(exist_ok=True)
    dest_name = f"vocab-harvester-{new_version}-setup.exe"
    dest_path = INSTALLER_DIR / dest_name
    shutil.copy2(installer_files[0], dest_path)
    installer_size = dest_path.stat().st_size / (1024 * 1024)

    # 清理临时目录
    shutil.rmtree(short_base, ignore_errors=True)

    print(f"\n{'='*50}")
    print(f"  vocab-harvester v{new_version} build complete!")
    print(f"  exe:       {DIST_DIR / 'vocab-harvester.exe'}")
    print(f"  installer: {dest_path} ({installer_size:.0f} MB)")
    print(f"{'='*50}")


if __name__ == "__main__":
    main()
