; Auto-generated by build_release.py - version 1.0.7
#define MyAppName "vocab-harvester"
#define MyAppVersion "1.0.7"
#define MyAppPublisher "VocabHarvester"
#define MyAppExeName "vocab-harvester.exe"
#define MySourceDir "C:/Users/lawgenesis-qh4k/.qoderwork/workspace/mqhrmv2w9de7mkno/outputs/vocab-harvester/dist/vocab-harvester"

[Setup]
AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:/Users/lawgenesis-qh4k/.qoderwork/workspace/mqhrmv2w9de7mkno/outputs/vocab-harvester/installer
OutputBaseFilename=vocab-harvester-1.0.7-setup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
SetupIconFile=C:/Users/lawgenesis-qh4k/.qoderwork/workspace/mqhrmv2w9de7mkno/outputs/vocab-harvester/icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "{#MySourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MySourceDir}\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; WorkingDir: "{app}"; Flags: nowait postinstall skipifsilent
